---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rdgen
  namespace: rdgen
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.4.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false
    TZ: America/Chicago
    resources:
      requests:
        cpu: 10m
    image:
      repository: docker.io/bryangerlach/rdgen
      pullPolicy: IfNotPresent
      tag: latest@sha256:be6068de6d4b5df0e04e2ca0423c72f9397c37cef1418cff796dbcedb79cce43
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0      
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${XMLTV_IP}
        integrations:
          metallb:
            enabled: true
        ports:
          main:
            port: 8000
            targetPort: 8000
            protocol: http            
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
                SECRET_KEY: "${RD_SECRET_KEY}"
                GHUSER: "${RD_GHUSER}"
                GHBEARER: "${RD_GHBEARER}"
                GENURL: rdgen.${DOMAIN_4}
                PROTOCOL: "https"
                REPONAME: "rdgen"
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: rdgen.${DOMAIN_4}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod              