apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:l0nSHkYIrbIMRt5so/U4Kz4JD6f6jzLH5+t4iZ620HliyHIXXWtbHA==,iv:uibfllBzwpn990J4AF/qzhzVjEoJWgv4EoLs0MrF4Pc=,tag:EC/RKULEawlwP66AAkRswg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kqqt7xkq7me5fdtr0pe800ul9tukgzsc8w4269lsxrnw9t02t4rqwvtxls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpazlOUUlIOEFiZDhTaG0w
            a0xZMTlFblhZZTF0RkU3N1F0aHJhLzRoYTBjCmpWckFoa2VNRCtkSDhCdndPOHJx
            VE1LcXpIQkwwMmVSZ3hHRHlBTzBEODQKLS0tIDVyQXdVb2drNG95VGF3YUVoZUx6
            NGp2TitpV2NIMHRpWEZoaWQybFZuZmMKRSwKNOy4TrnwJ7j5UaKJKk3My9eagh6r
            Bo7ns9tCrbf5OQThBjcg4YWBRqxyR71HPqRQM8xG92954aoXW0+3tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T03:47:48Z"
    mac: ENC[AES256_GCM,data:ce49bh4TJSsKHXMdvmRcoIbTP41ClWPRnC79b72Y0p+NmF3twfiIHrMuXYEb9Ir4vpwd5vngEFYUtLbr7k7JxC3JD9jhpBsDTT8oerEWOxjXncG9dJC2F1OeKmpig/xkKLVBqu4vVX+keB7aYjr2ZhaxYX+9mvAdNDyXgSPLM+Y=,iv:PUerQjhRCj9KaYXCTNjBBGbLooG90h0+6nj24ZxwIJ8=,tag:Cj12XLow89gSldG5XKyYQw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
