apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:j9m3WUZcm5NSK6X25yDZbqfyUDPNXgpKkSt6vOT8naac44QlaJnwlA==,iv:mnXPWu4vkLOLAk8/bpqqc5Bkelf+RPoG35O24H2c2v8=,tag:UBf62wKtbTLc5KJtjTrg+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadkMrQ0NJcVJBemtzZUVK
            RGRscG50ZnFldG1Ic3ZMbXNiM29BblRrekNRCmd1SmJLYkt4NXNTVjZhcDRiVms3
            ZnY5MzJxUFY0VUV0Nmhubmh3UU13U0EKLS0tIGZKbkpFYURPdzdrMUhZNm1KNGli
            MnVwMS9Gbk9EcUF6QW9lTmhtZStBTXMKvz/+zRddKBg9tgMBpLIkS4Kes6XMXId0
            O5/81Z80kgKdBGrRsweSG85VnoFB2jMOjb98INWdoQ16fgAk7V3HMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-13T18:27:35Z"
    mac: ENC[AES256_GCM,data:+7UXwW+Oseb8dzMmj+3W4JCMQ7hOdI5Qksm/hBHBY4XLbM/3KQ77czYGQE3eexRKEWl9Vtk15iyhyXWTn7TrRy3/iN/pHlzvhGVN6feWEruUCssFuoUC/noKf/MHJaE7OnhL01v+QQMPHqlgBOzgDVVYqJ9dPBmdawHcwMQT3DI=,iv:9U786lwkD9n+a07Vv+3yeXNazi3OuzWvtkU6wetb0UU=,tag:c5L8c9fNmrh12TQks/9IFg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
