apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hprawi0ZvXZXS0uLTjRYrCd2PqDqkHGylovrE0IugsrD8qlhmLXxBQ==,iv:Fli/wFD+qi29AFvUsKgo8I74WTksohT34nGMX1PMcxI=,tag:fVIamT4qqjpHiihcNkjbhA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kqqt7xkq7me5fdtr0pe800ul9tukgzsc8w4269lsxrnw9t02t4rqwvtxls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcVJQWEJyK2lKWVlkUTJO
            T2lZSUJtaXFORWRxemIyTTJqME12N2FnbWdnCnkxSFhYWEtkWEZyVFQvTkU2NVE3
            LzNRWDR2c0RXKys1Umt4UGwyV24yODAKLS0tIFhBZ0IzN2Y5UWRCc21QMHB6K1hK
            QVc1alBxY3NTVzNQTkYxTkpIWHlDR00K5fLIGHo1L7G67/eMhin/kavU0v56i7C/
            d/IZrNwwV8pGthobhE5aJnbIY68NNydbYEoakpxPDfch0TS392zkcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-17T19:34:45Z"
    mac: ENC[AES256_GCM,data:ULOR3dbwpSLqiX+jG7IrqlIWGG2u84UiIdBRXUyxLDmqxjrww79SVhwprMt3x+eOL0CWN074xK5GlukMutJK7RyuJOQILYrS5+6XLDnpzH/JoZHv/XPpt+2pykCZ1dT+VwTC8sAo3fALeawLazTkaVHHxt76WeN4ZeFBPUOLYE4=,iv:gT6oJZzMxDSk2otn1I1M3fO/oWiYR55ZusweHRynU6s=,tag:bMaE/iIOx5RXShGMx/CKFg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
