clusterName: ${CLUSTERNAME}
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.10.5
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.33.3
endpoint: https://${VIP}:6443
allowSchedulingOnControlPlanes: false
additionalMachineCertSans:
    - 127.0.0.1
    - ${VIP}
additionalApiServerCertSans:
    - 127.0.0.1
    - ${VIP}
# Warning: Also used in Cilium CNI values!
clusterPodNets:
    - ${PODNET}
clusterSvcNets:
    - ${SVCNET}
cniConfig:
    name: none
patches:
    - '@./patches/all.yaml'
nodes:
    # We would adivce to always stick to a "k8s-something-1" style naming scheme
    - hostname: k8s-control-1
      ipAddress: ${MASTER1IP_IP}
      controlPlane: true
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
      installDiskSelector:
        size: <= 1600GB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: eth0
          addresses:
            - ${MASTER1IP_CIDR}
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-control-2
      ipAddress: ${MASTER2IP_IP}
      controlPlane: true
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: eth0
          addresses:
            - ${MASTER2IP_CIDR}
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}  
    - hostname: k8s-control-3
      ipAddress: ${MASTER3IP_IP}
      controlPlane: true
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
      installDiskSelector:
        size: <= 1TB
      schematic:
          customization:
              systemExtensions:
                  officialExtensions:
                      - siderolabs/qemu-guest-agent
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: eth0
          addresses:
            - ${MASTER3IP_CIDR}
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-worker-1
      ipAddress: 192.168.2.207
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
      installDiskSelector:
        # size: <= 600GB
        model: Fan*
    - hostname: k8s-worker-2
      ipAddress: 192.168.2.206
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
      installDiskSelector:
        model: KIN*
    - hostname: k8s-worker-3
      ipAddress: 192.168.2.205
      nameservers:
        - 1.1.1.1
        - 8.8.8.8
      installDiskSelector:
        size: <= 200GB
      schematic:
          customization:
              systemExtensions:
                  officialExtensions:
                      - siderolabs/qemu-guest-agent
controlPlane:
    patches:
        - '@./patches/controlplane.yaml'
    kernelModules:
     - name: nvme_tcp
     - name: vfio_pci
     - name: uio_pci_generic
    schematic:
        customization:
            extraKernelArgs:
                - net.ifnames=0
            systemExtensions:
                officialExtensions:
                    - siderolabs/util-linux-tools
                    - siderolabs/iscsi-tools
                    - siderolabs/intel-ucode 
    machineFiles:
    - content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
      permissions: 0
      path: /etc/cri/conf.d/20-customization.part
      op: create
    - content: |
        [ NFSMount_Global_Options ]
        nfsvers=4.2
        hard=True
        nconnect=16
        noatime=True
      permissions: 420
      path: /etc/nfsmount.conf
      op: overwrite

worker:
    patches:
        - '@./patches/worker.yaml'
    kernelModules:
     - name: nvme_tcp
     - name: vfio_pci
     - name: uio_pci_generic
    schematic:
        customization:
            systemExtensions:
                officialExtensions:
                    - siderolabs/util-linux-tools
                    - siderolabs/iscsi-tools
                    - siderolabs/intel-ucode 
    machineFiles:
    - content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
      permissions: 0
      path: /etc/cri/conf.d/20-customization.part
      op: create
    - content: |
        [ NFSMount_Global_Options ]
        nfsvers=4.2
        hard=True
        nconnect=16
        noatime=True
      permissions: 420
      path: /etc/nfsmount.conf
      op: overwrite
