---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stun-turn
  namespace: stun-turn
spec:
  interval: 15m
  chart:
    spec:
      chart: stun-turn-server
      version: 9.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    TZ: America/Chicago
    resources:
      requests:
        cpu: 10m    
    service:
      main:
        enabled: true
        loadBalancerIP: ${TURN_IP}
        type: LoadBalancer
        integrations:
          metallb:
            enabled: true
        ports:
          main:
            enabled: true
            port: 3478
            protocol: tcp
            targetPort: 3478
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
          nginx.ingress.kubernetes.io/websocket-services: "stun-turn"
          nginx.ingress.kubernetes.io/upstream-hash-by: "$binary_remote_addr"              
        hosts:
          - host: turn.${DOMAIN_1}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod         
