---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  interval: 15m
  chart:
    spec:
      chart: speedtest-tracker
      version: 8.2.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Chicago
    resources:
      requests:
        cpu: 10m    
    global:
      stopAll: false    
    credentials:
      s3:
        type: s3
        url: "${MINIO_S3URL}"
        bucket: "${MINIO_S3PREFIX}-speedtest"
        accessKey: "${MINIO_S3ID}"
        secretKey: "${MINIO_S3KEY}"
        encrKey: "${MINIO_S3KEY}"       
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: speedtest.${DOMAIN_1}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod         
    persistence:
      config:
        storageClass: ceph-filesystem
        size: 1Gi
        accessModes:
          - ReadWriteMany       
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              volumeSnapshotClassName: ceph-filesystem               
              enabled: true
            src:  
              volumeSnapshotClassName: ceph-filesystem            
              enabled: true
              trigger:
                schedule: "15 23 * * *"
    cnpg:
      main:
        # mode: recovery   # Set to 'recovery' when recovery from S3, also change the revisions 
        backups:
          enabled: true
          credentials: s3
          scheduledBackups:
            - name: daily-backup
              schedule: "0 20 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false           
          retentionPolicy: "14d"
          revision: "1"
        recovery:
          method: object_store
          credentials: s3
          revision: "1"
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PUBLIC_DASHBOARD: false
                CHART_DATETIME_FORMAT: "d.m H:i"
                DATETIME_FORMAT: "d.m.Y H:i"
                SPEEDTEST_SCHEDULE: "0 * * * *"
                PRUNE_RESULTS_OLDER_THAN: 90
                DISPLAY_TIMEZONE: "America/Chicago"
                SPEEDTEST_SERVERS: "32338"      