apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Lh/Q4m9IuhKDw+ydrxK9ra+jJqCYhOduf712CUtGELc4lvve51Xvz//iGsA6EPOy0oziIezDtp6bMeCFgX8Z009ObUk9JsoD1zKafe0xRCxGOv/F8SJKq0/av9iMmRRQdR1phGmGTykYv1W81Ixblmn44pBYTNsrqwwrAXez4aUAJWCVrZKN6N0QfBFlz1l3x2cHEEfFYVM4qYuFpFIje8lIiGXjlt0qdHbV7hJuf1qJFolK2Ox1zVLYLRHMkr58q823KIEVjKU3/TUr3yyQhu7T8ZKrGZaIvAnmCKi3DPf4H99w4ZZMmY3Wvxnt8cpgtjOkP9oXwvcoI06KD9KKRAAgcdmNCu8ExLdV/h69taCvB2etpqBZ9YnOIUj61XKA,iv:IHTecZVNSKK27t4Vz6dP+Bd7X5FnJ2lJ4Pma7uJtwQ0=,tag:Mw4yFmDQbRSA8F6Vd8TYVA==,type:str]
    identity.pub: ENC[AES256_GCM,data:fHT/N53gnkKia64xbiSBlt9yLB03f0RlFrAQkseO6fTniBQ0sbyqf4gB7vJIlITdBkged9Cvo9He/r3QC2KsnV2NG2D6oY7g2VQXC6HmtYp2GQ+FaftzIaNPBL94mF/3JiXcMIsklni5JH4mwOmvfkE398DYFexW4eZTAkbwL0cJpy17VUjhUPIjkqVBIQTzu/9z9Ecu+i+Dw1pvEGE5SPK3KrwgT5h/u4/UM4WZp58VV8L8pmVe6eFXAj5TIKXi5AaXc0Q5bWv5ixLIpw==,iv:N0tXA7Fg13z3kQ+IZ6zOwJqAY11dIqkv8AlvrEVztRk=,tag:S/s9Iqddcu2+PGI/b/ANdw==,type:str]
    known_hosts: ENC[AES256_GCM,data:9ENxWEQIepKNUp1UPoC3RioTzpUnUzEhGvhOzykmOAMH2Hx0KnmLdYu5HdNVfRlfZYeEuVLQAZWcaPLm3nnp7Wi8wwc5uMf/ggbuv4LVCTQvnFOd+iMzVX34bzHBmzhG2BjhbMI7JKCh2+PP87fYfkyRau5pjZaJ9oYHhgw1FT7/UbE7FQRe6gG6KPj65UjJW+lU/UUtLB/C2KwL/3+bNhGG37TWEX1IE8D2,iv:BHioA1FYIj/xAetigQs4AB9Db6QP+oYXiolLsy1y8+Q=,tag:GTd3uQye0m5+7mgianRzsw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1kqqt7xkq7me5fdtr0pe800ul9tukgzsc8w4269lsxrnw9t02t4rqwvtxls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMHZIOHdFczdyT01VamFu
            a3FEazd5OEtFK0ExZFArQUJGVEZuS2p3SjM4Ck5KckROYndmUGI3VzB1MDV6WjhO
            YlY0OE91SFVKcGx1SUNrbXdmTVE2WlkKLS0tIGVCalRCZ3hwa0lwMUljdVg1Qi82
            QysvSDhmSGRrQks4UnNJanBOQmZibzAKDODAgxfxT1dFS/pFbQCPqAsev1C6xyYx
            vZXsRAEUNzRVwS+r3m9m2Fd31ImuIxek/iz+9L3VbSLVD8lEIvIBvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T04:37:18Z"
    mac: ENC[AES256_GCM,data:8W4KpUwKd60xaLO9rnz95SNAcRygrQ+SK+2Aizc/XiNDOb1U+1UopsgIcRVJp5INxFW0ZR8tLCKNw4pSqmkrV9uFDIgez0MNnhJJ/cR4eZ9xnLVq7Q0zPhFWv3VQNuRgOA5T1pX87RjFhGWlArEOjrru3aWq4429FpoTo902HAY=,iv:30WeoxmGGDkgJcJiwiDu1IlW+nbA8wEEV/vcM7d81Xw=,tag:HuZrS5yE9rtp4sknj2nWMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
