apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GX2rAT9lyq+bM6a6IAyK0zWCfM3KORMqJ+aWuBwgCcZaBRYIYSqfKW1gexAGqaZHlqEbRqf/jfyuQXE4S58td+rz/JV83qGC3zTcDXc5GvLo4M/Ukt9C1POurtOv3vxyWEOW5YVppn681Q/IwxZgtaQL6qRt14LBSVKvtlhqQ00Xl72dXu+eyFRD412k/lZafEDNoGziBA/wR9aOQvr+8Cp0qweK/qIwjdqauvvFlDMySon9DsUuljd4DOSK8CnXN7PAB/RG1hj3tXqGYU25rHHyr90JHVfuSuMpt7FnFI43UkbfhOdEhb7diEeXUA7ZpgqxkykXqwY+qr8knxwtb4lenV84do66MtXHEQuOMnozzvi3lMpz0XAz5A2CurfP,iv:VkcfakNVT2b8pSMr6uRJywj//21meeKpS4XdntV9Fsg=,tag:K/gogVVc4kaoVBen2HNpEA==,type:str]
    identity.pub: ENC[AES256_GCM,data:j+IWX8615iZIU+k1DPgln7v3q52CJqwLq7FLLCTr2pMUQrbjLwiS5ryV1K5FQBYMualhel8mmDfDbhs/l+en/InFVB40ljjO1hxQQqebCyW8E4lLZGHk6A6+s3Z+jYCJ+VyAe4XpWk/HXiBn2e+lTS5G8Mmx2eLklQqoQalpfQQQ6K4K+obNRQlJmdoabw8BntqfonBkF6rU6qQygxh4soUs7gCXN/D+AdccLGGflIaYxUwoU8lhxEkKVkM5yz+c2WtP7jssYmeguMrZtw==,iv:Maq+NhterxT6vw83VdQwDgccmzGWPctRM6D5A1foqHY=,tag:65acjfQRVO4LDys4hLaHRw==,type:str]
    known_hosts: ENC[AES256_GCM,data:B3sAabBvM4X9HWVv5I95mASB2JgzYF8qmUPILF2w+GmYo2FS0Pbiu7p11Yia8r0WrWmooeTEL8M6na8hM/d+bAxrFThKZeSoecqwnoM4r13kjfwOGArmpWu1safDrm8bKnjYnbCQpvQfMtJ76K5r4xVF1uXp94mXNth/BP+OTA2cQ6LkJRZjuW4IR8K6P4ZN+2SXpdD5PLHdI+qIVX179FO679p4ELJl36bV,iv:AsaD8jaBGyRdOWrjkg0VbHTT9CmjURXHu/0ITgarRDw=,tag:OyKQYAlliEGNbf+n7Y2KHg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RVFmU2xseWtwVFFhaDdK
            eWFrcjRIN2toVWZ4WVIvWDVMV0NxWVMwdFVNCjdoNTZwU3l0MzFHK1MxZ0ZkNE1Y
            SHZZcHFtY3lsOVVTekQwY3I5U1RVRWsKLS0tIHJQeHU4TUdwKzE3R0JIS3RrYlNQ
            TTVFZUhIR1lJTW5DSFg2d05rWDJGYmcKy1JlnspdmrCcs7TK09cwBjtblwNxXfa0
            MZ62AsL5aPRCnHyJIFKEOF9J8gocUdmc6EhtdmbaL6iTUkY/N8R83Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-25T21:57:58Z"
    mac: ENC[AES256_GCM,data:h2dNiQAGy0ZmKUpxWzc63IzS3FTrN29jLVC8OvBNe8gFiO4tLR+o1wIjeJT5l3pXkPvjG5vjQF/goWXgeiCfxfXM3vLXrD2+BP8TxaLCUKVl05FJ78fEZLcBzQGGINxgW8VwbA+DgdKpZtG8Qlubk/GWKIbFcoB80zVFR9McEj4=,iv:05P+kHjIlxoL8nW85JYuL7CLwXwWwFFS8NvT9V+PB2w=,tag:+ueRIJ3PDhYEEiRa6OT6mA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
