apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9yJ41Dw/3iXxDmI3gW6JVRDXtDNN759lAP+c6wIxlaXcD7O8m/5bktdFoEGfLe7Kd+RRawwIHFCsuX1Qw7GDVd/GQa4myFWmFDJ5KoPCbvJCF/KEUtkEbLQeuK9512Y3t2H6KL8/9uyIpOrPECUG+iQU1DT6OiSK5yWmB2FV+VeUJsQL0OvGQSmntTJgyOhTxSAtcpOhVufT2TLXS+3wRdTWNh36votnqwKp8fiq8S1/bXLuHVzL0IAoLxb5mbrAVpxHuiHSvS9NKblh8XStsKDj80L1lzdVC+lnWuUHikPV4Awt7+17C9UCzToGKmJQpC2NVwJp/zyFvo0ZARoLj4glm74cTSF8glgaOBqd4eDJqf4UOigXwrGwV6UOOvdk,iv:3M20TAsdtzrJds4BRcAYaIQnhXsdM/itZt+cc3Kayas=,tag:wqqkfR8+xCtZHzmX6+cfcQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:f/aKxRtSnjfcBFEkZibmiNZeGr2vyLEhQwJDSeDdy4bBMXtsk8WcNJ0Xuf2pBdyoXBasX15A0/9O+0DAnhIYRVwjdCh2l1vq0UqvuaKgLGavNTFOwmbb0Eh2wAzx2bGyYlPsOUFPryLMW0fFqGTQZHrhNpl9WZL30rOKjoJPNhDF6MUbCMr4+MKfQg8MaJSmUuQodkbyPiLxsB82Y6AuvghVAwXaWi+dMzOfPVZb0QYZ7nJ8odb8zY3v0ZDV4J7awwGrUpEIthx8RLMuBQ==,iv:YFGLcLOyja7wQ09ol3dunBH5BI38LkaN7gSMwcNqr5w=,tag:fXQyk95APKEUmMt6sW6m0w==,type:str]
    known_hosts: ENC[AES256_GCM,data:wUdcPfyxh1nLwXgHAJBnBqDFkSxTpSsCDabqJ23Cqda3qr9fTePryWljuDRA/uKzg/Eat0GHeojI/PSvfqgUbs9+ogPjtl5e6s/cWJlzKbR2AoMdqGcY0AYxjRiD8tperM55ojs+2NbjXhlcD/IIRHQPcsaIw1vInu1buMOgtiPQyO3CqDUH2qpVTq/yxOIsI2AKsHfeSOiT0rVkjJS0GaOEiMR8RDiivNCe,iv:zWvg3h2moPX4CuD66HPsNpwtEXk7H++vdIpP6cZMXF4=,tag:pXb1ewzl+eDgLexWNYOEog==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZjVaZU9zcXRJdmR0R0Zk
            TWFnMjNJN1d2MXBUY1FSZWZsUXlZd2Z4YVFrCllUbU50SmpRenpTai9xRVIwenFB
            Q0MwRFFWMjdOUFQwTy9aOWVUUE45eVkKLS0tIHdtYk96b2RZVTJJU1c4aFdUN1ly
            bGJRc3dVREIzVWxhWTRBdEdod3RNR2MKBD8cBCUruOBNR1aldHc7uXXFpThi1WEH
            YuAZ/vO9PFYVtlBGRbAgxIND7P/kD3SfInSTxmq+DbCSbC/ppqWFEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ahhpeqda220h75jh8fwfptlze88sggr70lu3vzzylhj9phtm730sj06q7m
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-03T14:22:38Z"
    mac: ENC[AES256_GCM,data:RBMXto1wznBDeuqX2YO2rPGYR4DVqWo2UAs51ZbpTlYT5YYt4MuiXErTMmCTKdyr2prTk3BWX+FK7hGk3gIszl4jL71tQ1uBQtBKdFTUGxz1GkF4Yd3PpKBq3gHJ2Znk60oHHEjFOEjstcCRoPaHY2x7BWz2bQa0fYQh7LC6trI=,iv:8OOGIvnlHmuC2Q92FBwsq4DgihVg6ZO/n/T6RuGd1o8=,tag:TL0tAC5t1RsdoqLXmVlG6Q==,type:str]
    shamir_threshold: 3
    version: 3.13.1
