apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hass
  namespace: hass
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: 28.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ## Enable host networking for direct network access. True breaks K8s security.
    # hostNetwork: true
    TZ: America/Chicago 
    resources:
      requests:
        cpu: 10m      
    global:
      stopAll: false 
    credentials:
      s3:
        type: s3
        url: "${MINIO_S3URL}"
        bucket: "${MINIO_S3PREFIX}-hass-rwx"
        accessKey: "${MINIO_S3ID}"
        secretKey: "${MINIO_S3KEY}"
        encrKey: "${MINIO_S3KEY}"
    service:
      main:
        enabled: true
        loadBalancerIP: ${HASS_IP}
        type: LoadBalancer
        integrations:
          metallb:
            enabled: true
        ports:
          main:
            enabled: true
            port: 8123
            protocol: tcp
            targetPort: 8123
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: ha.${DOMAIN_1}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod  
    homeassistant:
      trusted_proxies:
      - 172.16.0.0/16
      - 172.17.0.0/16
    persistence:
      config:
        storageClass: ceph-filesystem
        size: 1Gi
        accessModes:
          - ReadWriteMany        
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              volumeSnapshotClassName: ceph-filesystem
              enabled: true
            src:
              volumeSnapshotClassName: ceph-filesystem 
              enabled: true
              trigger:
                schedule: "30 14 * * *"      
      zigbeedongle:
        enabled: true
        type: device
        hostPath: /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_0001-if00-port0              

    workload:
      main:
        # type: Deployment
        # strategy: RollingUpdate #ToDo install a second zigbee dongle 
        # replicas: 2      
        podSpec:
          nodeSelector:
            feature.node.kubernetes.io/usb-ff_10c4_ea60.present: "true"
            
         
