apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: nextcloud
    namespace: nextcloud
spec:
    interval: 15m
    chart:
        spec:
            chart: nextcloud
            version: 32.8.6
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 15m
    timeout: 20m
    maxHistory: 3
    driftDetection:
        mode: warn
    install:
        createNamespace: true
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        global:
            stopAll: false
        TZ: America/Chicago
        cnpg:
            main:
                backups:
                    credentials: s3
                    enabled: true
                    retentionPolicy: ""
                    revision: "2"
                # mode: recovery
                monitoring:
                    disableDefaultQueries: false
                    enablePodMonitor: true
                password: ${NEXTCLOUD_CNPG_PWD}
                pgVersion: 15
                scheduledBackups:
                  - name: daily-backup
                    schedule: "0 25 17 * * *"
                    backupOwnerReference: self
                    immediate: true
                    suspend: false
                recovery:
                    credentials: s3
                    enabled: true
                    # revision: "3"
                    serverName: ""
                user: nextcloud
        credentials:
          s3:
            type: s3
            url: "${S3URL}"
            bucket: "${S3PREFIX}-nextcloud"
            accessKey: "${S3ID}"
            secretKey: "${S3KEY}"
            encrKey: "${S3KEY}"
        ingress:
            main:
                enabled: true
                hosts:
                    - host: testcloud.${DOMAIN_1}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: cloudflare
                        enabled: true
                    # homepage:
                    #     description: ""
                    #     enabled: true
                    #     group: Apps
                    #     icon: ""
                    #     name: ""
                    #     widget:
                    #         custom:
                    #             key: ""
                    #         enabled: false
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
        nextcloud:
            credentials:
                initialAdminPassword: ${ADMIN_PASSWORD}
                initialAdminUser: admin
            general:
                accessIP: ${TRUENAS_IP}
                default_phone_region: US
            notify_push:
                enabled: true
        persistence:
            config:
                volsync:
                    - credentials: s3
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                        trigger:
                          schedule: 0 15 * * *
                      type: restic
            data:
                enabled: true
                path: /mnt/data1/nc_userdata
                readOnly: false
                server: ${TRUENAS_IP}
                type: nfs
            html:
                volsync:
                    - credentials: s3
                      dest:
                        enabled: true
                      name: html
                      src:
                        enabled: true
                        trigger:
                          schedule: 0 15 * * *
                      type: restic

