---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mydocuseal
  namespace: mydocuseal
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.7.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false
    TZ: America/Chicago
    resources:
      requests:
        cpu: 10m
    image:
      repository: docker.io/mooneydude/docuseal
      pullPolicy: Always
      tag: latest
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: sign.${DOMAIN_1}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod   
          nginx:
            enabled: true
            auth:
              type: "authentik"
              disableSignIn: true
              internalHost: "authentik-http.authentik.svc.cluster.local:10230"
              externalHost: "sign.${DOMAIN_1}"   

    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
    service:
      main:
        ports:
          main:
            port: 10310
            protocol: http
            targetPort: 3000

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                DATABASE_URL:
                  secretKeyRef:
                    name: cnpg-main-urls
                    key: std
              probes:
                liveness:
                  type: http
                  path: /
                readiness:
                  type: http
                  path: /
                startup:
                  type: http
                  path: /

    persistence:
      data:
        enabled: true
        mountPath: /data

    cnpg:
      main:
        enabled: true
        user: docuseal
        database: docuseal
       

