---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ext-cow
  namespace: ext-cow
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 16.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Chicago
    global:
      stopAll: false
    service:
      main:
        type: ExternalIP
        externalIP: ${COW_IP}
        integrations:
          metallb:
            enabled: true
        ports:
          main:
            protocol: http
            port: 80
          # http:
          #   protocol: http
          #   port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "${DOMAIN_3}"
          - host: "${DOMAIN_5}"
          - host: "${DOMAIN_6}"
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod