---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: vaultwarden
      version: 28.6.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false

    TZ: America/Chicago
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-vault"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"       
    ingress:
      main:
        enabled: true
        hosts:
          - host: myvault.${DOMAIN_1}
        integrations:
          traefik:
            enabled: true
            # middlewares:
            #   - name: local
            #     namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: cloudflare 
    vaultwarden:
        allowSignups: false
        verifySignup: false
        requireEmail: false
        allowInvitation: true
        showPasswordHint: false
        enableWebVault: true
        admin:
          enabled: true
          disableAdminToken: false
          token: ${VW_TOKEN}
        smtp:
          enabled: false
          host: smtp.gmail.com
          from: ${EMAIL}
          fromName: Dude
          security: starttls
          port: 587
          heloName: Vault
          timeout: 15
          invalidHostname: false
          invalidCertificate: false
          user: ${EMAIL}
          password: ${VW_SMTP_PWD}
    persistence:
      data:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
    cnpg:
      main:
        # password: ${VAULTWARDEN_CNPG_PWD}
        #mode: recovery
        backups:
          enabled: true
          credentials: s3
          revision: "1"
          retentionPolicy: "7d"
        recovery:
          method: object_store
          credentials: s3
          revision: "1"  
