apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellyfin
    namespace: jellyfin
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: jellyfin
            version: 21.1.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    timeout: 20m
    values:
      TZ: America/Chicago
      resources:
        requests:
          cpu: 10m         
      portal:
        open:
          enabled: false
      global:
        stopAll: false
      credentials:
        s3:
          type: s3
          url: "${MINIO_S3URL}"
          bucket: "${MINIO_S3PREFIX}-jellyfin-rwx"
          accessKey: "${MINIO_S3ID}"
          secretKey: "${MINIO_S3KEY}"
          encrKey: "${MINIO_S3KEY}"
      ingress:
        main:
          enabled: true
          ingressClassName: internal
          hosts:
            - host: tv.${DOMAIN_1}
          integrations:
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod  
      persistence:
        config:
          storageClass: ceph-filesystem
          size: 1Gi
          accessModes:
            - ReadWriteMany           
          volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              volumeSnapshotClassName: ceph-filesystem
              enabled: true
            src:
              volumeSnapshotClassName: ceph-filesystem
              enabled: true